name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths: ["*.py"]

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: docker://ghcr.io/kciter/aws-ecr-action:latest
      with:
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        repo: devsecops-task
        region: eu-central-1
        dockerfile: Dockerfile
        tags: latest,${{ github.sha }}
        extra_build_args: --platform=linux/amd64
